site_name: Swampy Marsh
site_url: https://example.com/
nav:
    - Home: index.md
    - About:
      - 'About': 'about/about.md'
      - 'Staff': 'about/staff.md'

theme: 
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
  extra:
    version:
      provider: mike
      default: stable
