site_name: Swampy Marsh
site_url: https://the-swampy-marsh.readthedocs.io
nav:
    - Home: index.md
    - About:
      - 'History': 'about/history.md'
      - 'Staff': 'about/staff.md'

theme: 
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top