site_name: Swampy Marsh
site_url: https://example.com/
nav:
    - Home: index.md
    - About:
      - 'History': 'about/history.md'
      - 'Staff': 'about/staff.md'

theme: 
  name: material
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.instant
extra:
  version:
    provider: mike